#!/bin/bash

cat > $0.mpp <<EOF
<html>
<head><title>Test.</title></head>
<body>
<h1>Bonjour!</h1>
{< let x = 10 >}
<table>{<
let () =
  for i = 0 to 10 do
    print_string "<tr>";
    for j = 0 to 10 do
      let r = if j = 0 then i else if i = 0 then j else (i*j) in
        Printf.printf "<td>%d</td>" r
    done;
    print_string "</tr>\n";
  done
>}</table>
</body>
</html>
EOF

cat > $0.expected <<EOF
<html>
<head><title>Test.</title></head>
<body>
<h1>Bonjour!</h1>


<table>
<tr><td>0</td><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td></tr>
<tr><td>1</td><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td></tr>
<tr><td>2</td><td>2</td><td>4</td><td>6</td><td>8</td><td>10</td><td>12</td><td>14</td><td>16</td><td>18</td><td>20</td></tr>
<tr><td>3</td><td>3</td><td>6</td><td>9</td><td>12</td><td>15</td><td>18</td><td>21</td><td>24</td><td>27</td><td>30</td></tr>
<tr><td>4</td><td>4</td><td>8</td><td>12</td><td>16</td><td>20</td><td>24</td><td>28</td><td>32</td><td>36</td><td>40</td></tr>
<tr><td>5</td><td>5</td><td>10</td><td>15</td><td>20</td><td>25</td><td>30</td><td>35</td><td>40</td><td>45</td><td>50</td></tr>
<tr><td>6</td><td>6</td><td>12</td><td>18</td><td>24</td><td>30</td><td>36</td><td>42</td><td>48</td><td>54</td><td>60</td></tr>
<tr><td>7</td><td>7</td><td>14</td><td>21</td><td>28</td><td>35</td><td>42</td><td>49</td><td>56</td><td>63</td><td>70</td></tr>
<tr><td>8</td><td>8</td><td>16</td><td>24</td><td>32</td><td>40</td><td>48</td><td>56</td><td>64</td><td>72</td><td>80</td></tr>
<tr><td>9</td><td>9</td><td>18</td><td>27</td><td>36</td><td>45</td><td>54</td><td>63</td><td>72</td><td>81</td><td>90</td></tr>
<tr><td>10</td><td>10</td><td>20</td><td>30</td><td>40</td><td>50</td><td>60</td><td>70</td><td>80</td><td>90</td><td>100</td></tr>
</table>
</body>
</html>

EOF

mpp -snl -its -l ocaml -w -o $0.ml.out < $0.mpp
ocamlc -w -24 -impl $0.ml.out -o $0.exe.out && ./$0.exe.out > $0.out

diff $0.out $0.expected

